# Generated by Django 4.0.5 on 2022-06-29 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoria', models.CharField(max_length=40)),
                ('detalleCategoria', models.TextField(max_length=200)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'ordering': ('nombreCategoria',),
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreOferta', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaTermino', models.DateField()),
                ('descuento', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
            ],
            options={
                'verbose_name': 'oferta',
                'verbose_name_plural': 'ofertas',
                'ordering': ('fechaInicio',),
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=40)),
                ('precio', models.PositiveIntegerField()),
                ('imagen', models.ImageField(upload_to='imagen/')),
                ('stock', models.PositiveSmallIntegerField()),
                ('descripcion', models.TextField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='producto.categoria')),
                ('idOferta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='producto.oferta')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ('creado',),
            },
        ),
    ]
