# Generated by Django 4.0.5 on 2022-07-01 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_idoferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oferta',
            name='descuento',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idOferta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.oferta'),
        ),
    ]
