# Generated by Django 4.0.5 on 2022-07-17 01:15

import apps.producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_oferta_descuento_alter_producto_idoferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(upload_to=apps.producto.models.nombreImagen),
        ),
    ]
