# Generated by Django 4.0.5 on 2022-07-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(default='fotos/foto-perfil-default.png', upload_to='fotos/'),
        ),
    ]
