# Generated by Django 4.0.5 on 2022-07-28 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_perfil_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
    ]
