# Generated by Django 4.0.5 on 2022-06-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(max_length=20)),
                ('retiro', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreProducto', models.CharField(max_length=60)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('precioTotal', models.PositiveIntegerField(default=0)),
                ('fechaBoleta', models.DateTimeField(auto_now_add=True)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'boleta',
                'verbose_name_plural': 'boletas',
                'ordering': ['id'],
            },
        ),
    ]
