# Generated by Django 4.0.5 on 2022-06-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='fechaBoleta',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='creado',
            field=models.DateField(auto_now_add=True),
        ),
    ]
