# Generated by Django 4.0.5 on 2022-06-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_boleta_fechaboleta_alter_pedido_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='numeroPedido',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
