# Generated by Django 4.0.5 on 2022-06-29 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_pedido_numeropedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='precioTotal',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
