# Generated by Django 4.0.5 on 2022-06-29 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_pedido_preciototal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='numeroPedido',
        ),
    ]
