# Generated by Django 4.0.5 on 2022-07-17 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_remove_pedido_numeropedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(default='', max_length=60),
        ),
    ]
