# Generated by Django 4.0.5 on 2022-07-17 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0006_pedido_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
    ]
